# Generated by Django 3.1.1 on 2022-07-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name_plural': 'Message'},
        ),
    ]
